### ISSUE TITLE
[suggestion] avg tx size per day

### ISSUE THREAD

**Issue by aeon1234** [stoffu/diff-chart#2]
after seeing that transactions in aeon mempool are currently bigger than transactions in xmr mempool, I'm very interested if this is always the case or if this is just a variance.

there are also a lot of tx with 54 inputs, which are clearly bigger than others. these maybe belong to exchange [bittrex.com](https://www.bittrex.com).

[aeon.lol](https://www.aeon.lol) `no of txs: 219, size: 2812.95 kB`  =>  12.84 kB / tx
[xmrchain.com](https://www.xmrchain.com) `no of txs: 24, size: 66.23 kB`  =>  2.75 kB / tx

![aeon](https://user-images.githubusercontent.com/39473497/58570101-a2580380-8237-11e9-9e06-d206d0861a45.png)
![xmr](https://user-images.githubusercontent.com/39473497/58570115-a6842100-8237-11e9-9ec3-4948f7a7266a.png)

**Comment by stoffu** [comment]
Added in 3695fd06499e61610d09109f483b1cf1815534ce

![Screen Shot 2019-09-13 at 13 54 32](https://user-images.githubusercontent.com/26077532/64838425-13c49200-d62e-11e9-80d8-f59d9c7c7829.jpg)
https://stoffu.github.io/diff-chart/aeon-tx-per-day-1.html
